version: "3.3"

services:
  node:
    image: ghcr.io/carmentis/node.carmentis:latest
    environment:
      - CARMENTIS_NODE_URL=${CARMENTIS_NODE_URL:-https://mercurius.carmentis.io}
      - CARMENTIS_NODE_NAME=${CARMENTIS_NODE_NAME:-MERCURIUS}
      - CARMENTIS_NODE_DATABASE_DIR=${CARMENTIS_NODE_DATABASE_DIR:-/carmentis/app/node/db}
      - CARMENTIS_NODE_STORAGE_DIR=${CARMENTIS_NODE_STORAGE_DIR:-/carmentis/app/node/storage}
      - CARMENTIS_NODE_PLUGIN_DIR=${CARMENTIS_NODE_PLUGIN_DIR:-/carmentis/app/node/plugins}
      - CARMENTIS_NODE_KEY_FILE=${CARMENTIS_NODE_KEY_FILE:-/carmentis/app/node/carmentis.key}
      - CARMENTIS_CONFIG_FILE=${CARMENTIS_CONFIG_FILE:-/carmentis/config/config-docker.json}
    container_name: node.carmentis
    restart: unless-stopped
    tty: true
    volumes:
      - ./.data/node/storage:${CARMENTIS_NODE_STORAGE_DIR:-/carmentis/app/node/storage}
      - ./.data/node/db:${CARMENTIS_NODE_DATABASE_DIR:-/carmentis/app/node/db}
    networks:
      - carmentis_network
    ports:
      - "3004:3004"

networks:
    carmentis_network:
        driver: bridge
