version: "3.3"

services:
  cometbft:
    container_name: cometbft.carmentis
    image: ghcr.io/carmentis/cometbft.carmentis:latest
    ports:
      - "26656-26657:26656-26657"
      - "26670:26660"
    environment:
      - ID=0
      - CMTHOME=/cometbft
      - LOG=${LOG:-cometbft.log}
      - PROXY_APP=${PROXY_APP:-abci:3004}
      - MONIKER=${CARMENTIS_NODE_NAME:-TESTNODE0}
    networks:
      - carmentis_network
    volumes:
      - ./.carmentis/cometbft:/cometbft
#    command: ["/cometbft/cometbft"]
    #entrypoint: ["docker-entrypoint.sh"]

  abci:
    depends_on:
      - cometbft
    image: ghcr.io/carmentis/abci.carmentis:latest
    environment:
      - CARMENTIS_NODE_URL=${CARMENTIS_NODE_URL:-https://mercurius.carmentis.io}
      - CARMENTIS_NODE_NAME=${CARMENTIS_NODE_NAME:-MERCURIUS}
      - CARMENTIS_NODE_DATABASE_DIR=${CARMENTIS_NODE_DATABASE_DIR:-/carmentis/app/node/db}
      - CARMENTIS_NODE_STORAGE_DIR=${CARMENTIS_NODE_STORAGE_DIR:-/carmentis/app/node/storage}
      - CARMENTIS_NODE_PLUGIN_DIR=${CARMENTIS_NODE_PLUGIN_DIR:-/carmentis/app/node/plugins}
      - CARMENTIS_NODE_KEY_FILE=${CARMENTIS_NODE_KEY_FILE:-/carmentis/app/node/carmentis.key}
      - CARMENTIS_NODE_PORT=${CARMENTIS_NODE_PORT:-3004}
      - CARMENTIS_NODE_PROTO_DIR=/carmentis/app/node/proto
    container_name: abci.carmentis
    restart: unless-stopped
    tty: true
    volumes:
      - ./.carmentis/abci/storage:${CARMENTIS_NODE_STORAGE_DIR:-/carmentis/app/node/storage}
      - ./.carmentis/abci/db:${CARMENTIS_NODE_DATABASE_DIR:-/carmentis/app/node/db}
    networks:
      - carmentis_network
    ports:
      - "3004:3004"

networks:
    carmentis_network:
        driver: bridge
